name: miniproj_2
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - backports.zstd=1.3.0
  - beautifulsoup4=4.14.3
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - ca-certificates=2025.11.12
  - certifi=2025.11.12
  - charset-normalizer=3.4.4
  - h2=4.3.0
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=78.1
  - idna=3.11
  - ld_impl_linux-64=2.45
  - libexpat=2.7.3
  - libffi=3.5.2
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - liblzma=5.8.1
  - libnsl=2.0.1
  - libsqlite=3.51.1
  - libstdcxx=15.2.0
  - libuuid=2.41.3
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.6.0
  - pip=25.3
  - pysocks=1.7.1
  - python=3.12.12
  - python_abi=3.12
  - readline=8.3
  - requests=2.32.5
  - setuptools=80.9.0
  - soupsieve=2.8.1
  - tk=8.6.13
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - tzdata=2025c
  - urllib3=2.6.2
  - wheel=0.45.1
  - zstd=1.5.7


